### ISSUE TITLE
renBTC stuck on the way back to Ethereum(updated tx)

### ISSUE THREAD

**Issue by cmx250** [solana-labs/oyster#248] opened 2021-09-03 15:56 UTC
RenBTC stuck on the way back to Ethereum.

I can't find the tx on the page because there's some kind of web page bug where the tx table is on an infinite loading loop

i believe the tx is this one:
https://explorer.solana.com/tx/2oE36wASyUszkWUBfCgmfJVUGvamNkM6Wa4ckw7K3M878NduAdKBFLGvYrbAotxB2p9QUuCv6uZx4jPCBk2MqXHE

although it is hard to check due to tx table not loading.

**Comment by yamijuan** [comment] 2021-09-03 17:14
did you connect both wallets and selected renBTC before checking the table?

**Comment by cmx250** [comment] 2021-09-03 17:28
Yes I did. thats when the loading icon shows up and never goes away
![image](https://user-images.githubusercontent.com/90019448/132044656-dfbbf770-1dcd-408d-a5fe-1fb7aac165d5.png)

My setup:
Ethereum - firefox+Metamask
Solana - Phantom Wallet

Funnily enough if i try to use brave with a similar setup the connect button on the ethereum side doesnt work at all.

**Comment by pseudoanonymous-eth** [comment] 2021-09-05 04:36
Did you get this resolved? I have the exact same issue, spinning wheel on recent transaction and everything.

**Comment by pseudoanonymous-eth** [comment] 2021-09-06 06:17
The issue is you need to call "Submit VAA" from your ETH address with the proper byte code
this person @hx8888979 wrote a script to generate that byte code based on your solana TX. try it https://www.interstellar.tk/
I was able to use it no problem, so am sharing it to others with this issue
they put the option to tip fyi, if it all works well for you

**Comment by leoluk** [comment] 2021-09-06 12:24
The transaction you provided failed with "insuffcient funds". Please provide the correct tx which transferred out your funds.

**Closed by leoluk** 2021-09-06 12:24 UTC
