### ISSUE TITLE
Please add wBBTC to drop down list

### ISSUE THREAD

**Issue by maxitimes** [solana-labs/oyster#200] opened 2021-08-24 13:37 UTC
I tried transferring BTC from Ethereum to Solana using the Wormhole and ended up with wBBTC which is not usable on Solana.  

I currently am unable to do anything with it as it is not recognised as BTC on Solana.  Please add wBBTC to the Solana drop down so i can return it to Ethereum  

tx is here : https://solscan.io/token/3UeKTABxz9XexDtyKq646rSQvx8GVpKNwfMoKKfxsTsF#holders

Token is : 3UeKTABxz9XexDtyKq646rSQvx8GVpKNwfMoKKfxsTsF
Binance Wrapped BTC (Wormhole) (wBBTC)

Or alternatively return an identical amount of usable BTC to my account.  

Thank you

**Comment by leoluk** [comment] 2021-08-28 15:49
Duplicate of https://github.com/solana-labs/oyster/issues/201

**Closed by leoluk** 2021-08-28 15:49 UTC
